kind: pipeline
type: kubernetes
name: scrapoxy

steps:
- name: docker  
  image: plugins/docker
  settings:
    registry: rg.nl-ams.scw.cloud
    username: nologin
    password:
      from_secret: docker_password
    repo: rg.nl-ams.scw.cloud/laffin
    dockerfile: Dockerfile

trigger:
  branch:
  - develop
  event:
  - push